language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "pypy3"
# I have removed testing on pypy3 until it reaches 3.4.

# command to install dependencies
install: "python setup.py develop"

# command to run tests
script: "python setup.py test"
